User_Authentication/Login_2/application/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path,urandom
from flask_login import LoginManager

BASE_DIR = path.abspath(path.dirname(__file__))
DB_NAME = 'auth.db';

db = SQLAlchemy()

def create_app():

    app = Flask(__name__);

    app.config['SECRET_KEY'] = '%s'%(urandom(100));
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+path.join(BASE_DIR,DB_NAME);
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = 0;
    
    db.init_app(app);


    from .views import views;
    from .login_view import login_auth;

    app.register_blueprint(views,url_prefix='/');
    app.register_blueprint(login_auth,url_prefix='/');

    from .Db_model import SCHOOL;
    
    create_db(app)

    login_manager = LoginManager()
    login_manager.login_view = 'login_auth.login';
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(user_id):
        print(user_id)
        return SCHOOL.query.get(int(user_id))

    return app;

def create_db(app):
    if not path.exists('application/'+DB_NAME):
        db.create_all(app=app);
    else:
        pass 
    return 1

User_Authentication/Login_2/application/views.py
from flask import Blueprint,render_template  


views = Blueprint('views',__name__);


@views.route('/')
def home():
    return render_template('home.html',name='Home');

@views.route('/about')
def about():
    return render_template('about.html',name='About');

User_Authentication/Login_2/application/templates/about.html
{% extends 'base.html' %}

{% block title %}
{{ super() }} {{name}}
{% endblock title %}


{% block heading %}

<h1>{{name}}</h1>

{% endblock heading %}

{% block content %}



{% endblock content %}

User_Authentication/Login_2/application/templates/alert_msg.html
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}

<div class="alert alert-danger" role="alert">
    {{ message }}
</div>

{% endfor %}
{% endif %}
{% endwith %}

User_Authentication/Login_2/application/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        auth
        {% endblock title %}
    </title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital@1&display=swap');
        
        *{
            font-family: 'Poppins', sans-serif;
        }
                        
    </style>
</head>

<body>

    {% include 'nav_bar.html' %}

    <div class="position-relative">
        <div class="position-absolute top-100 start-50 translate-middle">
            {% block heading %}<h1>Null Page</h1> {% endblock heading %}
        </div>
    </div>



    {% block content %}
    {% endblock content %}

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

User_Authentication/Login_2/application/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}
{{name}}
{% endblock title %}

{% block heading %}

<h1>Hi {{name}}</h1>


{% endblock heading %}


{% block content %}
{% include 'alert_msg.html' %}

{%  include 'table.html' %}

{% endblock content %}

User_Authentication/Login_2/application/templates/form_log.html
<head>
    <link rel="stylesheet" href="static/style.css">
  <style>
    .middle {
      background: wheat;
    }
  </style>
</head>

<div class="container middle">
  <form method="post">
    {{xfor.hidden_tag()}}
    <div class="mb-3">
      {{xfor.email(class_="form-control")}}
    </div>
    <div class="mb-3">
      {{xfor.password(class_="form-control")}}
    </div>
    {{xfor.submit(class_="btn btn-primary")}}
  </form>
</div>

User_Authentication/Login_2/application/templates/form_reg.html
<head>
    <link rel="stylesheet" href="static/style.css">
  <style>
    .middle_2 {
      background: rgb(151, 204, 197);
    }
  </style>
</head>

<div class="container middle_2">
  <form method="post">
    {{xfor.hidden_tag()}}
    <div class="mb-3">
        {{xfor.username(class_="form-control")}}
      </div>
    <div class="mb-3">
      {{xfor.email(class_="form-control")}}
    </div>
    <div class="mb-3">
      {{xfor.password(class_="form-control")}}
    </div>
    <div class="mb-3">
        {{xfor.pass_conform(class_="form-control")}}
      </div>
    {{xfor.submit(class_="btn btn-primary")}}
  </form>
</div>

User_Authentication/Login_2/application/templates/home.html
{% extends 'base.html' %}

{% block title %}
{{ super() }} {{name}}
{% endblock title %}


{% block heading %}

<h1>{{name}}</h1>


{% endblock heading %}

{% block content %}



{% endblock content %}

User_Authentication/Login_2/application/templates/login.html
{% extends 'base.html' %}

{% block title %}
{{ super() }} {{name}}
{% endblock title %}


{% block heading %}

<h1>{{name}}</h1>


{% endblock heading %}

{% block content %}
{% include 'alert_msg.html' %}
{% include 'form_log.html' %}

{% endblock content %}

User_Authentication/Login_2/application/templates/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Authentication</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{{url_for('views.home')}}">Home</a>
          <a class="nav-link active" href="{{url_for('views.about')}}">About</a>
          <a class="nav-link active" href="{{url_for('login_auth.sign_up')}}">Register</a>
          <a class="nav-link active" href="{{url_for('login_auth.login')}}">Login</a>
        </div>
      </div>
    </div>
  </nav>

User_Authentication/Login_2/application/templates/signup.html
{% extends 'base.html' %}

{% block title %}
{{ super() }} {{name}}
{% endblock title %}


{% block heading %}

<h1>{{name}}</h1>

{% endblock heading %}

{% block content %}

{% include 'alert_msg.html' %}

{% include 'form_reg.html' %}

{% endblock content %}

User_Authentication/Login_2/application/templates/table.html
<head>
    <style>
        .table {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>



<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Email</th>
            <th scope="col">Date of singup</th>
            <th scope="col">Logout</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>{{name}}</td>
            <td>{{em}}</td>
            <td>{{dt}}</td>
            <td><a href="{{url_for('login_auth.logout')}}" type="button" class="btn btn-danger">Click</a></td>
        </tr>
    </tbody>
</table>